# Generated by Django 4.1.13 on 2025-01-30 20:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0003_alter_comment_options_alter_like_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'verbose_name': 'Фотография', 'verbose_name_plural': 'Фотографии'},
        ),
        migrations.AddField(
            model_name='comment',
            name='comment_user',
            field=models.ManyToManyField(blank=True, related_name='коомене', to=settings.AUTH_USER_MODEL),
        ),
    ]
