# Generated by Django 4.1.13 on 2025-02-08 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_remove_like_dislikes_like_likes_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(default=None, null=True, upload_to='static', verbose_name='Изображение'),
        ),
    ]
