# Generated by Django 5.0.2 on 2025-02-12 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0010_remove_like_likes_remove_like_likes_user_like_like_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='like',
            field=models.CharField(default='like', max_length=4),
        ),
    ]
