# Generated by Django 5.0.2 on 2025-02-12 16:18

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0011_alter_like_like'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime.now, null=True),
        ),
        migrations.RemoveField(
            model_name='message',
            name='comment_user',
        ),
        migrations.AddField(
            model_name='message',
            name='comment_user',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, related_name='коммент', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
