# Generated by Django 5.0.2 on 2025-02-12 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0012_message_created_at_remove_message_comment_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='comment',
            field=models.TextField(default='класс', max_length=300),
        ),
    ]
