# Generated by Django 5.0.2 on 2025-02-12 17:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0013_alter_message_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post_1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(default='прекрасное фото', max_length=256)),
                ('created_at', models.DateTimeField(default=datetime.datetime.now, null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='message',
            old_name='comment_user',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='message',
            name='comment',
            field=models.CharField(default='super', max_length=500),
        ),
    ]
