# Generated by Django 5.0.2 on 2025-02-12 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0017_post_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='comment',
        ),
    ]
