# Generated by Django 5.0.2 on 2025-02-14 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0021_post_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post_1',
            old_name='text',
            new_name='text_1',
        ),
    ]
