# Generated by Django 5.0.2 on 2025-02-14 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0022_rename_text_post_1_text_1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post_1',
            name='text_1',
            field=models.TextField(default='Хороший комментарий', max_length=256),
        ),
    ]
