# Generated by Django 5.0.2 on 2025-02-14 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0023_alter_post_1_text_1'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post_1',
            old_name='post',
            new_name='image',
        ),
        migrations.AlterField(
            model_name='post_1',
            name='text_1',
            field=models.TextField(default='Хороший комментарий', max_length=500),
        ),
    ]
