# Generated by Django 5.0.2 on 2025-02-15 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0025_rename_image_post_1_post_alter_post_1_text_1'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post_1',
            old_name='post',
            new_name='image',
        ),
    ]
