# Generated by Django 5.0.2 on 2025-02-17 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0028_alter_post_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='user',
            new_name='user_1',
        ),
    ]
