# Generated by Django 5.0.2 on 2025-02-17 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0029_rename_user_post_user_1'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='user_1',
            new_name='user',
        ),
    ]
